Replace laravel-mix with vite.js
wordplate/wordplate pull request #284
Opened 2022-01-16 09:47 UTC by vinkla

This is work in progress to replace Laravel Mix with Vite.js.

2022-01-17 11:47 UTC, puredazzle requested changes
We should use `defineConfig` in Vite to get autocomplete for the config.

```
import { defineConfig } from 'vite';

export default defineConfig(({ mode }) => ({
```

2022-01-17 12:30 UTC, puredazzle approved these changes
LGTM! Good job!

2022-01-18 14:47 UTC, fiskhandlarn commented
LGTM!

2022-01-18 14:49 UTC, fiskhandlarn requested changes

2022-01-18 14:49 UTC, fiskhandlarn commented on README.md
>  npm run build
`vite build`

2022-01-18 14:49 UTC, fiskhandlarn commented on README.md
>  npm run dev
`vite`

2022-01-18 17:54 UTC, vinkla commented on README.md
>  npm run build
We've added these as npm scripts.

2022-01-18 18:08 UTC, vinkla commented on README.md
>  npm run build
No worries!

2022-01-25 13:54 UTC, merged